# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nperrin <nperrin@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2014/11/03 19:45:10 by nperrin           #+#    #+#              #
#    Updated: 2015/03/12 14:54:41 by marene           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = 	libft.a

SRC = 	srcs/ft_btree/ft_btree_balance.c\
		srcs/ft_btree/ft_btree_infix.c\
		srcs/ft_btree/ft_btree_prefix.c\
		srcs/ft_btree/ft_btree_suffix.c\
		srcs/ft_btree/ft_btreeadd.c\
		srcs/ft_btree/ft_btreenew.c\
		srcs/ft_ctype/ft_isalnum.c\
		srcs/ft_ctype/ft_isalpha.c\
		srcs/ft_ctype/ft_isascii.c\
		srcs/ft_ctype/ft_isdigit.c\
		srcs/ft_ctype/ft_isprint.c\
		srcs/ft_ctype/ft_tolower.c\
		srcs/ft_ctype/ft_toupper.c\
		srcs/ft_io/ft_putchar.c\
		srcs/ft_io/ft_putchar_fd.c\
		srcs/ft_io/ft_putendl.c\
		srcs/ft_io/ft_putendl_fd.c\
		srcs/ft_io/ft_putnbr.c\
		srcs/ft_io/ft_putnbr_fd.c\
		srcs/ft_io/ft_putstr.c\
		srcs/ft_io/ft_putstr_fd.c\
		srcs/ft_io/ft_stdout.c\
		srcs/ft_io/get_next_line.c\
		srcs/ft_lib/ft_atoi.c\
		srcs/ft_lib/ft_itoa.c\
		srcs/ft_lib/ft_memalloc.c\
		srcs/ft_lib/ft_memdel.c\
		srcs/ft_list/ft_lst_len.c\
		srcs/ft_list/ft_lst_to_tab.c\
		srcs/ft_list/ft_lstadd.c\
		srcs/ft_list/ft_lstdel.c\
		srcs/ft_list/ft_lstdelone.c\
		srcs/ft_list/ft_lstiter.c\
		srcs/ft_list/ft_lstmap.c\
		srcs/ft_list/ft_lstnew.c\
		srcs/ft_string/ft_bzero.c\
		srcs/ft_string/ft_memccpy.c\
		srcs/ft_string/ft_memchr.c\
		srcs/ft_string/ft_memcmp.c\
		srcs/ft_string/ft_memcpy.c\
		srcs/ft_string/ft_memmove.c\
		srcs/ft_string/ft_memset.c\
		srcs/ft_string/ft_strcat.c\
		srcs/ft_string/ft_strchr.c\
		srcs/ft_string/ft_strclr.c\
		srcs/ft_string/ft_strcmp.c\
		srcs/ft_string/ft_strcpy.c\
		srcs/ft_string/ft_strdel.c\
		srcs/ft_string/ft_strdup.c\
		srcs/ft_string/ft_strequ.c\
		srcs/ft_string/ft_striter.c\
		srcs/ft_string/ft_striteri.c\
		srcs/ft_string/ft_strjoin.c\
		srcs/ft_string/ft_strlcat.c\
		srcs/ft_string/ft_strlen.c\
		srcs/ft_string/ft_strmap.c\
		srcs/ft_string/ft_strmapi.c\
		srcs/ft_string/ft_strncat.c\
		srcs/ft_string/ft_strncmp.c\
		srcs/ft_string/ft_strncpy.c\
		srcs/ft_string/ft_strndup.c\
		srcs/ft_string/ft_strnequ.c\
		srcs/ft_string/ft_strnew.c\
		srcs/ft_string/ft_strnstr.c\
		srcs/ft_string/ft_strrchr.c\
		srcs/ft_string/ft_strsplit.c\
		srcs/ft_string/ft_strstr.c\
		srcs/ft_string/ft_strsub.c\
		srcs/ft_string/ft_strtrim.c\
		srcs/ft_tab/ft_sort_tab.c\
		srcs/ft_tab/ft_tab_del.c\
		srcs/ft_tab/ft_tablen.c\
		srcs/libimage/ft_mlx.c\
		srcs/libimage/getcvect.c\
		srcs/libimage/getvect.c\
		srcs/libimage/img_delsurface.c\
		srcs/libimage/img_delwin.c\
		srcs/libimage/img_drawcline.c\
		srcs/libimage/img_init.c\
		srcs/libimage/img_newsurface.c\
		srcs/libimage/img_newwin.c\
		srcs/libimage/img_pixel_put.c\
		srcs/libimage/set_cline.c\
		srcs/libimage/set_line.c\
		srcs/libimage/setcpoint.c\
		srcs/libimage/setpoint.c\
		srcs/libimage/img_win_put.c\
		srcs/libimage/img_drawctriangle.c\
		srcs/ft_errno/ft_errno.c\
		srcs/ft_errno/ft_perror.c\
		srcs/ft_errno/ft_strerror.c

OBJ = 	ft_atoi.o\
		ft_bzero.o\
		ft_isalnum.o\
		ft_isalpha.o\
		ft_isascii.o\
		ft_isdigit.o\
		ft_isprint.o\
		ft_itoa.o\
		ft_lstadd.o\
		ft_lstdel.o\
		ft_lstdelone.o\
		ft_lstiter.o\
		ft_lstmap.o\
		ft_lstnew.o\
		ft_lst_len.o\
		ft_lst_to_tab.o\
		ft_memalloc.o\
		ft_memccpy.o\
		ft_memchr.o\
		ft_memcmp.o\
		ft_memcpy.o\
		ft_memdel.o\
		ft_memmove.o\
		ft_memset.o\
		ft_putchar.o\
		ft_putchar_fd.o\
		ft_putendl.o\
		ft_putendl_fd.o\
		ft_putnbr.o\
		ft_putnbr_fd.o\
		ft_putstr.o\
		ft_putstr_fd.o\
		ft_strcat.o\
		ft_strchr.o\
		ft_strclr.o\
		ft_strcmp.o\
		ft_strcpy.o\
		ft_strdel.o\
		ft_strdup.o\
		ft_strequ.o\
		ft_striter.o\
		ft_striteri.o\
		ft_strjoin.o\
		ft_strlcat.o\
		ft_strlen.o\
		ft_strmap.o\
		ft_strmapi.o\
		ft_strncat.o\
		ft_strncmp.o\
		ft_strncpy.o\
		ft_strnequ.o\
		ft_strnew.o\
		ft_strnstr.o\
		ft_strrchr.o\
		ft_strsplit.o\
		ft_strstr.o\
		ft_strsub.o\
		ft_strtrim.o\
		ft_tolower.o\
		ft_toupper.o\
		ft_strndup.o\
		ft_stdout.o\
		ft_sort_tab.o\
		ft_tablen.o\
		ft_tab_del.o\
		ft_btreenew.o\
		ft_btreeadd.o\
		ft_btree_prefix.o\
		ft_btree_infix.o\
		ft_btree_suffix.o\
		ft_btree_balance.o\
		get_next_line.o\
		ft_mlx.o\
		getcvect.o\
		getvect.o\
		img_delsurface.o\
		img_delwin.o\
		img_drawcline.o\
		img_init.o\
		img_newsurface.o\
		img_newwin.o\
		img_pixel_put.o\
		img_drawctriangle.o\
		set_cline.o\
		set_line.o\
		setcpoint.o\
		setpoint.o\
		img_win_put.o\
		ft_errno.o\
		ft_perror.o\
		ft_strerror.o

FLG	=	-Wall -Werror -Wextra

INC	=	includes/

all		: $(NAME)

$(NAME)	:
		gcc -c -g $(SRC) $(FLG) -I $(INC)
		ar rc $(NAME) $(OBJ)
		ranlib $(NAME)

clean	:
	rm -f $(OBJ)

fclean	: clean
	rm -f $(NAME)

re		: fclean $(NAME)
